name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy: { matrix: { os: [ ubuntu, macOS ] } }
    steps:
      - uses: actions/checkout@v2
      - run: npm cit
